# 1: Read The File Into A String

# Instructions
Use the open() function with the following parameters to return a File object:
dq_unisex_names.csv for the file name
r for read mode
Then, use the read() method of the File object to read the file into a string.
Assign that string to a variable named names.
Hint
In the open() function, we first pass in the file name, then the mode. Both must be string values.

In [25]:
f = open('dq_unisex_names.csv', 'r', encoding='utf-8')
names = f.read()
print(names)

Casey,176544.3281
Riley,154860.6652
Jessie,136381.8307
Jackie,132928.7887
Avery,121797.4195
Jaime,109870.1873
Peyton,94896.39522
Kerry,88963.92625
Jody,80400.5192
Kendall,79210.87396
Payton,64151.63039
Skyler,53486.39042
Frankie,51288.06811
Pat,44781.60237
Quinn,41920.94006
Harley,41237.56574
Reese,36360.52061
Robbie,32636.04765
Tommie,29528.79382
Justice,27350.56457
Kris,24955.81134
Carey,24790.09705
Emerson,24167.15436
Blair,23160.1011
Amari,22296.16137
Elisha,22184.55937
Sage,21336.06228
Emery,18844.11888
Stevie,18665.21912
Rowan,18367.42046
Ollie,17889.75034
Shea,16768.89188
Jaylin,15093.19204
Phoenix,14841.36788
Charley,12546.26578
Armani,12541.66776
Devyn,12515.02307
Ivory,11908.58071
Kendal,11841.40348
Baby,11132.85575
Mckinley,10972.53341
Finley,10194.61887
Milan,9971.955937
Tory,9837.844335
Shay,9444.894035
Shiloh,8999.08523
Lavern,8776.346296
Sky,8386.640072
Reilly,8300.824693
Leighton,8281.601797
Santana,7922.713789
Arden,7773.14736
Campbell,7728.956865
Channing,7626.335577
Kamari,7584.893909
Alva,7496.35069
Clair,7148.894728
Lavon,7107.834786
Kenyatta,7063.611274
Britt,6852.95455
Vernell,6729.462903
Michal,6558.698679
Austyn,6228.961465
Rian,6139.851241
Dominque,6101.13501
Remy,6094.667878
Jammie,6013.444775
Ricki,5847.272146
Jordin,5770.788278
Trinidad,5747.944235
Ryley,5685.538724
Carrol,5513.606968
Landry,5449.51046
Lorin,5428.15538
Yael,5232.374916
Codi,4805.328209
Sloan,4796.882097
Jael,4472.71492
Kodi,4428.704313
Azariah,4420.560847
Dakotah,4388.852023
Lorenza,4249.273719
Artie,4230.139897
Maxie,4123.46784
Torey,4058.588974
Tai,4017.916297
Kalani,4012.316123
Codie,3998.816987
Storm,3960.537446
Jaedyn,3913.076884
Merritt,3843.56067
Allyn,3801.332806
Jourdan,3781.556602
Yuri,3774.699243
Ellery,3738.814883
Oakley,3728.798329
Gentry,3703.829157
Ellison,3651.546836
Arin,3634.974321
Sol,3624.980544
Carrington,3616.3836
Dell,3615.033276
Carlin,3554.951422
Lennie,3533.447279
Dru,3445.961147
Alpha,3406.676728
Kiran,3405.697622
Tristyn,3336.366181
Camdyn,3274.913501
Krishna,3270.049176
Demetrice,3200.883393
Berkley,3184.659274
Linden,3155.870202
Mikah,3094.063238
Parris,3064.315071
Kalin,3021.240034
Kary,3020.968706
Arie,3014.123001
Aries,2964.756533
Rio,2960.443801
Sutton,2930.892868
Rhyan,2900.188369
Isa,2895.497837
Arlyn,2893.945006
Karsen,2872.427405
Seneca,2856.367471
Callan,2809.37665
Garnett,2797.598866
Micaiah,2749.93498
Christan,2684.978836
Aris,2549.033763
Tylar,2540.224111
Brighton,2534.958718
Merlyn,2500.628691
Kimani,2492.695778
Salem,2484.362235
Barrie,2480.799063
Braylin,2476.689792
Charly,2473.36083
Ocean,2470.958543
Ara,2398.501272
Deane,2395.830649
Andree,2375.252032
Natividad,2343.481904
Ardell,2327.065702
Divine,2322.744419
Ocie,2299.24497
Lakota,2298.545252
Ashtin,2291.99335
Larkin,2267.588897
Kamdyn,2266.011067
Waverly,2239.462468
Claudie,2203.604469
Lannie,2182.972994
Vernie,2155.660129
Adair,2154.719944
Kaidyn,2139.577902
Verdell,2133.742154
Jae,2106.066765
Aven,2090.059497
Kodie,2069.638392
Shalom,2060.595874
Daylin,2036.196151
Osiris,1997.239288
Dwan,1990.646038
Lashaun,1977.848391
Ashten,1969.697594
Dann,1959.445874
Shai,1950.991705
Teegan,1945.936273
Micha,1927.975901
Tobie,1921.187635
Jaelin,1910.944988
Marlowe,1893.814455
Kareen,1865.710053
Ryen,1827.655074
Marquette,1795.238032
Joell,1787.318885
Adel,1776.564727
Golden,1763.136515
An,1746.029349
Ossie,1740.230779
Stephane,1724.789877
Vinnie,1711.276531
Armoni,1707.359443
Berlin,1675.592169
Thanh,1671.332281
Jimi,1666.012608
Linn,1654.747322
Marvis,1653.1578
Tam,1647.93815
Kaylon,1644.939332
Kylin,1642.510785
Lajuan,1642.21941
Cameran,1611.747981
Shamari,1601.241909
Teddie,1595.122202
Laramie,1594.631205
Ricci,1585.31257
Jule,1555.296916
Cedar,1552.70581
Drue,1547.492989
Shade,1544.88143
Jeryl,1538.032514
Taylen,1535.983379
Devonne,1534.988374
Delane,1525.850038
Arnell,1518.343435
Earlie,1510.680394
Tenzin,1464.873785
Kendel,1464.373914
Arlis,1462.083094
Ashby,1459.223405
Shia,1450.051376
Berkeley,1447.964706
Lin,1434.757899
Freedom,1419.588662
Rylin,1405.565656
Aaryn,1391.675478
Mykah,1378.630611
Shaya,1373.047244
Tanis,1363.088001
Chancey,1357.860017
Jaidan,1353.840217
Jaydyn,1344.56751
Kaedyn,1342.72329
Talyn,1333.103591
Le,1323.979515
Hartley,1321.569286
Avon,1318.747786
Finnley,1313.456526
Schyler,1311.405147
Rennie,1307.957688
Aly,1298.699031
Kaydin,1293.967349
Camari,1292.573614
Clemmie,1288.247856
Payson,1280.568167
Anay,1278.824199
Devine,1270.283725
Terryl,1263.728601
Bao,1262.070243
Tru,1259.054676
Indiana,1241.572392
Evyn,1234.89999
Deniz,1226.69535
Emari,1223.375248
Davi,1218.88119
TRUE,1201.182194
De,1198.993461
Samar,1195.441393
Kriston,1194.67094
Lian,1191.954576
Brittan,1182.231829
Torre,1176.840612
Shawne,1173.510439
Kailen,1172.899859
Aundra,1172.128503
Halen,1151.043395
Yuki,1144.030879
Marshell,1133.685172
Rivers,1130.701023
Jaziah,1129.100128
Amaree,1110.775383
Mycah,1110.674706
Toy,1108.941987
Tien,1107.223237
Adi,1098.595416
Callahan,1097.194313
Jazz,1093.761948
Reign,1090.493726
Burnice,1082.020651
Jamy,1080.584735
Lavaughn,1073.002013
Adrean,1069.982513
Cache,1066.235232
Britain,1065.194805
Dalyn,1058.212286
Dondi,1055.754497
Dallis,1055.194322
Nazareth,1049.117378
Nieves,1043.052359
Jireh,1040.386483
Collen,1039.818143
Onyx,1034.681915
Raynell,1033.123788
Sonnie,1029.946621
Lyrik,1021.240142
Marice,1011.157308
Lexington,1006.492185
Chi,1000.513531
Eliyah,999.527175
Tonnie,989.239862
Teagen,979.78441
Rudi,970.191498
Kamani,953.566213
Han,951.241973
Jerre,950.874985
Alika,947.321531
Monta,941.063796
Jaydn,935.74131
Hadyn,926.30121
Kem,914.46861
Terrin,910.7775
Wisdom,909.725025
Natale,901.864284
Rossie,892.806341
Lugene,888.284575
Rebel,884.024521
Blayke,882.234279
Donyell,872.649431
Myrl,869.491606
Kaelen,862.728436
Miko,851.474358
Elza,847.576302
Kriss,835.690001
Shadow,825.52436
Raylen,818.709884
Ramey,811.497395
Jaryn,806.521407
Laren,804.308316
Leverne,802.818101
Khali,802.633638
Reiley,800.337736
Jaydee,798.057272
Luan,797.245459
Reily,796.287263
Caidyn,794.561122
Kaylor,794.271472
Juel,790.093471
Amrit,786.642927
Rayn,784.341578
Arien,782.936684
Britten,777.750504
Bela,760.563821
Arliss,758.632888
Aziah,758.497597
Lonie,755.868642
Pasha,748.990463
Caylen,748.902375
Talin,745.096319
Shaune,741.347119
Valen,735.983288
Ozie,735.766434
Dung,735.265634
Avry,731.426697
Zamari,729.95515
Kam,728.774296
Ronit,726.408001
Kelin,719.439015
Teigan,714.664818
Sun,714.643067
Karlin,713.305261
Lenell,702.26537
Jaleen,700.570415
Amory,698.662333
Loghan,692.909696
Kemani,692.781324
Aarin,692.676825
Elizah,692.517245
Maysen,689.180053
Yu,683.489357
Bergen,682.925024
Jalani,673.616259
Jamille,673.479423
Adama,672.71467
Laray,665.522256
Sully,665.517623
Latrelle,665.308862
Onnie,664.357223
Khanh,662.75548
Amil,661.805231
Braylyn,661.552177
Tanay,661.063212
Kailan,659.232761
Caelin,659.158099
Alexandr,656.239956
Daryan,656.138076
Wallis,654.622062
Kelechi,648.648494
Javonne,646.051594
Gean,645.994681
Kao,645.458334
Cypress,642.754615
Tamari,639.320661
Evann,634.337944
Tarren,632.967007
Jeffie,627.715909
Amel,625.482374
Jaspreet,623.708833
Amen,623.660314
Neema,617.783584
Hien,613.08858
Lorren,612.715537
Jonel,612.650548
Kelyn,610.690619
Jodeci,608.175239
Alexy,607.478474
Jayln,606.543254
Chayanne,601.107466
Brittain,598.385006
Selby,595.127455
Akili,591.896442
Kimari,591.479976
Anmol,590.472412
Kirin,590.139974
Min,589.129682
Eri,587.186027
Bralyn,582.769557
Alyn,582.742595
Osie,580.951667
Shiva,580.950328
Kamerin,580.529332
Pheonix,578.351431
Abrar,576.900756
Darnelle,573.536531
Haydin,572.946492
Davonne,559.431911
Makana,556.047924
Ayomide,554.577639
Daine,554.40281
Avrey,541.782016
Truth,541.390661
Uchenna,539.67233
Gracin,537.308384
Chong,536.896691
Marrion,536.009629
Atley,535.308139
Luverne,534.767742
Lunden,534.000961
Manpreet,533.557713
Kodee,533.325804
Kyri,530.500126
Donnelle,530.211598
Koree,529.952254
Riyan,528.259191
Sagan,526.849373
Teran,523.613117
Avory,522.679555
Lior,520.632626
Hoa,519.884708
Alexx,519.454611
Arleigh,515.496346
Brier,514.257293
Lyndall,513.422172
Terin,510.907222
Kallan,509.422604
Maika,505.696628
Trayce,504.464568
Deavion,502.716145
Indy,501.475923
Ellington,500.417504
Feliz,498.528778
Alexiz,498.397451
Neftaly,498.136952
Kaegan,495.71034
Edris,495.269629
Harpreet,495.17132
Jailin,489.922734
Mackinley,489.579285
Kendle,489.30663
Donyae,487.302887
Koi,485.358666
Eastyn,483.916571
Vertis,483.073698
Shady,480.399537
Shondell,480.066762
Monti,479.724204
Ardie,478.622326
Londen,476.616207
Kayde,476.545451
Gabryel,476.224649
Chai,475.693434
Gurpreet,475.593432
Tomie,473.437588
Corley,472.934632
Mishael,469.77639
Shalin,469.497742
Shann,465.469714
Lyndal,462.991251
Jamani,461.954209
Chee,460.36613
Deshay,460.068319
Devlyn,459.950086
Royale,457.356489
Jaidin,450.60592
Dayan,449.437503
Jari,447.90736
Amarii,445.041457
Dilyn,444.089446
Yuval,441.627245
Toryn,441.53306
Rajah,441.097798
Tatem,438.839865
Chidera,438.682476
Amarri,437.771104
Rielly,436.043049
Bobie,435.771001

# 2: Convert The String To A List

# Instructions
Use the split() method that strings have to split on the new-line delimiter ("\n"), and assign the resulting list to names_list.
Select the first five elements in names_list, and assign them to first_five.
Display first_five using the print() function.
Hint
Recall that you need to run the split() method on a specific string (e.g. string.split("_")).
Use bracket notation to display the first five elements in a list (e.g. list[0:5]).

In [28]:
names_list = names.split('\n')
first_five = names_list[0:5]
print(first_five)

['Casey,176544.3281', 'Riley,154860.6652', 'Jessie,136381.8307', 'Jackie,132928.7887', 'Avery,121797.4195']

# 3: Convert The List Of Strings To A List Of Lists

# Instructions
Split each element in names_list on the comma delimiter (,) and append the resulting list to nested_list. To accomplish this:
Create an empty list and assign it to nested_list.
Write a for loop that iterates over names_list.
Within the loop body, run the split() method on each element to return a list (assign that list to comma_list).
Within the loop body, run the append() method to add each list (comma_list) to nested_list.
Use the print() function to display the first five elements in nested_list.
Hint
In the loop, the iterator variable will also be a string, and will have the split() method.
To add a value to an existing list, use the append() method on that list and pass the value in.

In [30]:
nested_list = []

for nl in names_list:
    comma_list = nl.split(",")
    nested_list.append(comma_list)
print(nested_list[0:5])

[['Casey', '176544.3281'], ['Riley', '154860.6652'], ['Jessie', '136381.8307'], ['Jackie', '132928.7887'], ['Avery', '121797.4195']]

# 4: Convert Numerical Values

# Instructions
Create a new list of lists called numerical_list where:
The element at index 0 for each list is the unisex name (as a string)
The element at index 1 for each list is the number of people who share that name (as a float)
To accomplish this:
Create an empty list and assign it to numerical_list.
Write a for loop that iterates over nested_list. In the loop body:
Retrieve the element at index 0 and assign it to a variable.
Retrieve the element at index 1, convert it to a float, and assign it to a variable.
Create a new list containing these two elements (in the same order).
Use the append() method to add this new list to numerical_list.
Finally, display the first five elements in numerical_list.
Hint
Each element (which we reference in the loop body using the iterator variable) is a list. If you use the iterator variable line, line[0] retrieves the element at index 0 and line[1] retrieves the element at index 1.
To convert a value to a float, use the float() function.
To create a new list containing the values assigned to two variables, use bracket notation: new_list = [var1, var2].

In [34]:
numerical_list = []

for nl in nested_list:
    list_str = nl[0]
    list_flt = float(nl[1])
    new_list = [list_str, list_flt]
    numerical_list.append(new_list)
print(numerical_list[0:5])

[['Casey', 176544.3281], ['Riley', 154860.6652], ['Jessie', 136381.8307], ['Jackie', 132928.7887], ['Avery', 121797.4195]]

# 5: Filter The List

In [41]:
thousand_or_greater = []

for nl in numerical_list:
    if nl[1] >= 1000:
        thousand_or_greater.append(nl[0])
print(thousand_or_greater[0:10])

['Casey', 'Riley', 'Jessie', 'Jackie', 'Avery', 'Jaime', 'Peyton', 'Kerry', 'Jody', 'Kendall']