# 1. Data Cleaning
Instructions Remove all rows where the value for horsepower is ? and convert the horsepower column to a float.
Assign the new Dataframe to filtered_cars.
Hint
Use the Series method astype to convert the column to float.

In [13]:
import pandas as pd
columns = ["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model year", "origin", " car name"]
cars = pd.read_table('auto-mpg.data.txt',names=columns, delim_whitespace=True)
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18,8,307,130.0,3504,12.0,70,1,chevrolet chevelle malibu
1,15,8,350,165.0,3693,11.5,70,1,buick skylark 320
2,18,8,318,150.0,3436,11.0,70,1,plymouth satellite
3,16,8,304,150.0,3433,12.0,70,1,amc rebel sst
4,17,8,302,140.0,3449,10.5,70,1,ford torino
5,15,8,429,198.0,4341,10.0,70,1,ford galaxie 500
6,14,8,454,220.0,4354,9.0,70,1,chevrolet impala
7,14,8,440,215.0,4312,8.5,70,1,plymouth fury iii
8,14,8,455,225.0,4425,10.0,70,1,pontiac catalina
9,15,8,390,190.0,3850,8.5,70,1,amc ambassador dpl
10,15,8,383,170.0,3563,10.0,70,1,dodge challenger se
11,14,8,340,160.0,3609,8.0,70,1,plymouth 'cuda 340
12,15,8,400,150.0,3761,9.5,70,1,chevrolet monte carlo
13,14,8,455,225.0,3086,10.0,70,1,buick estate wagon (sw)
14,24,4,113,95.00,2372,15.0,70,3,toyota corona mark ii
15,22,6,198,95.00,2833,15.5,70,1,plymouth duster
16,18,6,199,97.00,2774,15.5,70,1,amc hornet
17,21,6,200,85.00,2587,16.0,70,1,ford maverick
18,27,4,97,88.00,2130,14.5,70,3,datsun pl510
19,26,4,97,46.00,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25,4,110,87.00,2672,17.5,70,2,peugeot 504
21,24,4,107,90.00,2430,14.5,70,2,audi 100 ls
22,25,4,104,95.00,2375,17.5,70,2,saab 99e
23,26,4,121,113.0,2234,12.5,70,2,bmw 2002
24,21,6,199,90.00,2648,15.0,70,1,amc gremlin
25,10,8,360,215.0,4615,14.0,70,1,ford f250
26,10,8,307,200.0,4376,15.0,70,1,chevy c20
27,11,8,318,210.0,4382,13.5,70,1,dodge d200
28,9,8,304,193.0,4732,18.5,70,1,hi 1200d
29,27,4,97,88.00,2130,14.5,71,3,datsun pl510
...,...,...,...,...,...,...,...,...,...
368,27,4,112,88.00,2640,18.6,82,1,chevrolet cavalier wagon
369,34,4,112,88.00,2395,18.0,82,1,chevrolet cavalier 2-door
370,31,4,112,85.00,2575,16.2,82,1,pontiac j2000 se hatchback
371,29,4,135,84.00,2525,16.0,82,1,dodge aries se
372,27,4,151,90.00,2735,18.0,82,1,pontiac phoenix
373,24,4,140,92.00,2865,16.4,82,1,ford fairmont futura
374,23,4,151,?,3035,20.5,82,1,amc concord dl
375,36,4,105,74.00,1980,15.3,82,2,volkswagen rabbit l
376,37,4,91,68.00,2025,18.2,82,3,mazda glc custom l
377,31,4,91,68.00,1970,17.6,82,3,mazda glc custom
378,38,4,105,63.00,2125,14.7,82,1,plymouth horizon miser
379,36,4,98,70.00,2125,17.3,82,1,mercury lynx l
380,36,4,120,88.00,2160,14.5,82,3,nissan stanza xe
381,36,4,107,75.00,2205,14.5,82,3,honda accord
382,34,4,108,70.00,2245,16.9,82,3,toyota corolla
383,38,4,91,67.00,1965,15.0,82,3,honda civic
384,32,4,91,67.00,1965,15.7,82,3,honda civic (auto)
385,38,4,91,67.00,1995,16.2,82,3,datsun 310 gx
386,25,6,181,110.0,2945,16.4,82,1,buick century limited
387,38,6,262,85.00,3015,17.0,82,1,oldsmobile cutlass ciera (diesel)
388,26,4,156,92.00,2585,14.5,82,1,chrysler lebaron medallion
389,22,6,232,112.0,2835,14.7,82,1,ford granada l
390,32,4,144,96.00,2665,13.9,82,3,toyota celica gt
391,36,4,135,84.00,2370,13.0,82,1,dodge charger 2.2
392,27,4,151,90.00,2950,17.3,82,1,chevrolet camaro
393,27,4,140,86.00,2790,15.6,82,1,ford mustang gl
394,44,4,97,52.00,2130,24.6,82,2,vw pickup
395,32,4,135,84.00,2295,11.6,82,1,dodge rampage
396,28,4,120,79.00,2625,18.6,82,1,ford ranger
397,31,4,119,82.00,2720,19.4,82,1,chevy s-10

In [14]:
filtered_cars = cars[cars['horsepower'] != '?']
filtered_cars.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 397
Data columns (total 9 columns):
mpg             392 non-null float64
cylinders       392 non-null int64
displacement    392 non-null float64
horsepower      392 non-null object
weight          392 non-null float64
acceleration    392 non-null float64
model year      392 non-null int64
origin          392 non-null int64
 car name       392 non-null object
dtypes: float64(4), int64(3), object(2)
memory usage: 30.6+ KB

In [15]:
filtered_cars['horsepower'] = filtered_cars['horsepower'].astype("float")
filtered_cars.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 397
Data columns (total 9 columns):
mpg             392 non-null float64
cylinders       392 non-null int64
displacement    392 non-null float64
horsepower      392 non-null float64
weight          392 non-null float64
acceleration    392 non-null float64
model year      392 non-null int64
origin          392 non-null int64
 car name       392 non-null object
dtypes: float64(5), int64(3), object(1)
memory usage: 30.6+ KB

//anaconda/envs/py35/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

# 2. Data Exploration
Instructions Use the Dataframe plot to generate a grid of subplots (2 rows by 1 column):
On the top plot, generate a scatter plot with the horsepower column on the x-axis and the mpg column on the y-axis.
On the bottom plot, generate a scatter plot with the weight column on the x-axis and the mpg column on the y-xis.
Hint
Use the Dataframe method plot to generate simple scatter plots. Documentation.

In [24]:
import matplotlib.pyplot as plt
filtered_cars.plot('horsepower', 'mpg', kind='scatter', c='red')
filtered_cars.plot('weight', 'mpg', kind='scatter', c='blue')
#plt.show()

# 3. Fitting A Model
Instructions Create a new instance of the LinearRegression model and assign it to lr.
Use the fit method to fit a linear regression model using the horsepower column as the input.
Use the model to make predictions on the same data the model was trained on (the horsepower column from filtered_cars) and assign the resulting predictions to predictions.
Display the first 5 values in predictions and the first 5 values in the mpg column from filtered_cars.
Hint
Don't forget to import LinearRegression from sklearn.linear_model.

In [25]:
import sklearn
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr.fit(filtered_cars[["horsepower"]], filtered_cars["mpg"])

predictions = lr.predict(filtered_cars[["horsepower"]])
print(predictions[0:5])
print(filtered_cars["horsepower"][0:5])

[ 19.41604569  13.89148002  16.25915102  16.25915102  17.83759835]
0    130
1    165
2    150
3    150
4    140
Name: horsepower, dtype: float64

# 4. Plotting The Predictions
Instructions Generate 2 scatter plots on the same chart (Matplotlib axes instance):
One containing the horsepower values on the x-axis against the predicted fuel efficiency values on the y-axis. Use blue for the color of the dots.
One containing the horsepower values on the x-axis against the actual fuel efficiency values on the y-axis. Use red for the color of the dots.
Hint
You can generate 2 scatter plots on one just by calling plt.scatter() twice and without creating any Axes objects manually.

In [26]:
plt.scatter(filtered_cars["horsepower"], predictions, c='red')
plt.scatter(filtered_cars["horsepower"], filtered_cars["mpg"], c='blue')
#plt.show()

# 5. Error Metrics
Instructions Calculate the MSE of the predicted values and assign to mse.
Calculate the RMSE of the predicted values and assign to rmse.
Hint
Recall that you need to import the mean_squared_error function from sklearn.metrics.

In [27]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(filtered_cars["mpg"], predictions)
print(mse)

23.9436629386

In [29]:
rmse = (mse) ** (1/2)
print(rmse)

4.89322623007